# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus:
  shortname: nicknguyen8
  layout: default
  comments: true
google_analytics: NickNguyen8
title: NickNguyen's blog

defaults:
  - scope:
      path: "" # empty string for all files
    values:
      title: NickNguyen's blog

description: NickNguyen's blog
author:
  name: Nick Nguyen
  email: nhnghe@gmail.com
  github: nicknguyen8
  twitter: nicknguyen_8
  facebook: nhnghe
  pinterest: nhnghe
  linkedin: nghenguyen
  bio: Live My Life
  email_md5: No

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: /dbyll
# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
